[package]
name = "fsr2"
description = "FidelityFX Super Resolution 2 bindings for rust."
version = "0.1.0"
edition = "2021"
authors = ["Embark <opensource@embark-studios.com>"]
license = "MIT"
repository = "https://github.com/EmbarkStudios/fsr2"

[dependencies]
widestring = "1.0"
bitflags = "1.3"
fsr2-sys = { path = "../fsr2-sys", default-features = false }

[dependencies.ash]
version = "0.37"
optional = true

[dependencies.windows]
version = "0.48"
optional = true
features = [
    "Win32_Graphics_Direct3D12"
]

[features]
default = []
vulkan = ["fsr2-sys/vulkan", "dep:ash"]
d3d12 = ["fsr2-sys/d3d12", "dep:windows"]
