/* automatically generated by rust-bindgen 0.69.4 */

extern "C" {
    #[link_name = "\u{1}ffxFsr2GetScratchMemorySizeDX12"]
    pub fn getScratchMemorySizeDX12() -> usize;
}
extern "C" {
    #[link_name = "\u{1}ffxFsr2GetInterfaceDX12"]
    pub fn getInterfaceDX12(
        fsr2Interface: *mut Interface,
        device: *mut ID3D12Device,
        scratchBuffer: *mut ::std::os::raw::c_void,
        scratchBufferSize: usize,
    ) -> ErrorCode;
}
extern "C" {
    #[link_name = "\u{1}ffxGetDeviceDX12"]
    pub fn getDeviceDX12(device: *mut ID3D12Device) -> Device;
}
extern "C" {
    #[link_name = "\u{1}ffxGetCommandListDX12"]
    pub fn getCommandListDX12(cmdList: *mut ID3D12CommandList) -> CommandList;
}
extern "C" {
    #[link_name = "\u{1}ffxGetResourceDX12"]
    pub fn getResourceDX12(
        context: *mut Context,
        resDx12: *mut ID3D12Resource,
        name: *const u16,
        state: ResourceStates,
        shaderComponentMapping: UINT,
    ) -> Resource;
}
extern "C" {
    #[link_name = "\u{1}ffxGetDX12ResourcePtr"]
    pub fn getDX12ResourcePtr(context: *mut Context, resId: u32) -> *mut ID3D12Resource;
}
